### ISSUE TITLE
GSoC 2017 - Working on this Project

### ISSUE THREAD

**Issue by devjayati** [zvr/clio#1]
I came across this project as a listing for GFOSS for GSoC 2017(https://ellak.gr/wiki/index.php?title=Clio) and found it very interesting. I tried making a basic frontpage layout (just the design, haven't coded it yet) and was wondering where to begin? (Microtasks that need to be completed). 
I have an intermediate knowledge of HTML/CSS.  
![clio](https://cloud.githubusercontent.com/assets/16128743/24335752/0c4f4d74-12a1-11e7-880f-9b342309701d.jpg)

Thank you!

**Comment by zvr** [comment]
Discussion on the project and the GSoC is happening on the opensource-devs@ellak.gr mailing list.
If you're interested in participating in GSoC, please read the list archives, as I've written many explanatory emails.
There is no list of microtasks -- there is one task, to implement the system.

**Comment by devjayati** [comment]
I sincerely apologize.
