### ISSUE TITLE
I wish to contribute to this project. Please guide me further.

### ISSUE THREAD

**Issue by NirmalKumarJoshi** [zvr/clio#4]
I can develop this application which will be totally secured and interactive for the user.

**Comment by NirmalKumarJoshi** [comment]
I have a great project plan that will surely make this application a very essential and efficient for the users.

**Comment by NirmalKumarJoshi** [comment]
I already ceated a pull request by developing the setup and configuring the database.Now starting with LDAP integration as per access control requirement

**Comment by zvr** [comment]
Thanks for your interest.
Please join the list at opensource-devs@ellak.gr (if you haven't done so yet) to follow the discussions.
