### ISSUE TITLE
I'm interested in this project and can develop it.

### ISSUE THREAD

**Issue by akshatbhargava123** [zvr/clio#6]
Please guide me how to make a proposal for this, I can develop whole application on MEAN stack which will be fully secure and efficient. Should we share a working prototype in proposal?

**Comment by zvr** [comment]
Thanks for your interest.
Please join the list at opensource-devs@ellak.gr (if you haven't done so yet) to follow the discussions.

**Comment by zvr** [comment]
Send an email to <opensource-devs+subscribe@ellak.gr>.
